SELECT * FROM genesys_2018.CIAT_crop_taxa;

delete  from genesys_2018.CIAT_crop_taxa;


CREATE TABLE `genesys_2018`.`CIAT_crop_taxa` (
  `crop` VARCHAR(45) NULL,
  `taxa` VARCHAR(45) NOT NULL,
  `rank` VARCHAR(45) NULL);
  
-- load crop and taxa relationship
INSERT INTO genesys_2018.CIAT_crop_taxa(crop, taxa, rank)
values ("Abaca","Musa","genus"),
("Achira","Canna","genus"),
("Ackee","Blighia","genus"),
("Adlay","Coix","genus"),
("Adzuki bean","Vigna","genus"),
("African rice","Oryza","genus"),
("Agave","Agave","genus"),
("Agropyron","Agropyron","genus"),
("Agrostis","Agrostis","genus"),
("Albardine","Lygeum","genus"),
("Alfalfa","Medicago","genus"),
("Allspice","Pimenta","genus"),
("Almonds","Prunus","genus"),
("Alopecurus","Alopecurus","genus"),
("Amaranth","Amaranthus","genus"),
("Andropogon","Andropogon","genus"),
("Anise","Pimpinella","genus"),
("Apple","Malus","genus"),
("Apricot","Prunus","genus"),
("Areca nuts","Areca","genus"),
("Arracacha","Arracacia","genus"),
("Arrhenatherum","Arrhenatherum","genus"),
("Arrowroot","Maranta","genus"),
("Artichokes","Cynara","genus"),
("Asian rice","Oryza","genus"),
("Asparagus","Asparagus","genus"),
("Astragalus","Astragalus","genus"),
("Atriplex","Atriplex","genus"),
("Avocado","Persea","genus"),
("Azarole","Crataegus","genus"),
("Babaco","Vasconcellea","genus"),
("Badian","Illicium","genus"),
("Bambara bean","Vigna","genus"),
("Bamboo shoot","Bambusa","genus"),
("Bamboo shoot","Phyllostachys","genus"),
("Bananas","Musa","genus"),
("Barley","Hordeum","genus"),
("Basil","Ocimum","genus"),
("Bay leaf","Laurus","genus"),
("Beech nut","Fagus","genus"),
("Beets","Beta","genus"),
("Black gram","Vigna","genus"),
("Black salsify","Scorzonera","genus"),
("Blueberry","Vaccinium","genus"),
("Brazil nut","Bertholletia","genus"),
("Breadfruit","Artocarpus","genus"),
("Buckwheat","Fagopyrum","genus"),
("Butter-nut","Caryocar","genus"),
("Butternut squash","Cucurbita","genus"),
("Cabbages","Brassica","genus"),
("Cabbages and other brassicas","Brassica","genus"),
("Caesarweed","Urena","genus"),
("Cainito","Chrysophyllum","genus"),
("Calabash","Lagenaria","genus"),
("Canary seed","Phalaris","genus"),
("Candlenut","Aleurites","genus"),
("Canola","Brassica","genus"),
("Capers","Capparis","genus"),
("Carambola","Averrhoa","genus"),
("Carapa","Carapa","genus"),
("Cardamoms","Amomum","genus"),
("Cardamoms","Elletaria","genus"),
("Carneros Yucca","Samuela","genus"),
("Carneros Yucca","Yucca","genus"),
("Caroa","Neoglaziovia","genus"),
("Carobs","Ceratonia","genus"),
("Carrots","Daucus","genus"),
("Cashews","Anacardium","genus"),
("Cassava","Manihot","genus"),
("Castor bean","Ricinus","genus"),
("Ceara","Manihot","genus"),
("Celery","Apium","genus"),
("Chayote","Sechium","genus"),
("Cherimoya","Annona","genus"),
("Cherries","Prunus","genus"),
("Chervil","Anthriscus","genus"),
("Chestnuts","Castanea","genus"),
("Chickpeas","Cicer","genus"),
("Chicle","Achras","genus"),
("Chicory","Cichorium","genus"),
("Chillies and peppers","Capsicum","genus"),
("Chinotto","Citrus","genus"),
("Chontadura","Astrocaryum","genus"),
("Chufa","Cyperus","genus"),
("Cinnamon","Cinnamomum","genus"),
("Citron","Citrus","genus"),
("Citronella","Cymbopogon","genus"),
("Clovers","Trifolium","genus"),
("Cloves","Syzygium","genus"),
("Cocoa","Theobroma","genus"),
("Coconuts","Cocos","genus"),
("Coffee","Coffea","genus"),
("Common bean","Phaseolus","genus"),
("Coriander","Coriandrum","genus"),
("Coronilla","Coronilla","genus"),
("Cotton","Gossypium","genus"),
("Cowpeas","Vigna","genus"),
("Cranberries","Vaccinium","genus"),
("Cress","Lepidium","genus"),
("Cucumbers and gherkins","Cucumis","genus"),
("Cumin","Cuminum","genus"),
("Currants","Ribes","genus"),
("Dactylis","Dactylis","genus"),
("Dates","Phoenix","genus"),
("Devil's cotton","Abroma","genus"),
("Dill","Anethum","genus"),
("Durian","Durio","genus"),
("Eggplant","Solanum","genus"),
("Elderberry","Sambucus","genus"),
("Esparto","Stipa","genus"),
("Ethiopian rape","Brassica","genus"),
("Faba beans","Vicia","genus"),
("Feijoa","Acca","genus"),
("Fennel","Foeniculum","genus"),
("Fenugreek","Trigonella","genus"),
("Festuca","Festuca","genus"),
("Figs","Ficus","genus"),
("Finger millet","Eleusine","genus"),
("Fique","Furcraea","genus"),
("Flax","Linum","genus"),
("Fonio","Digitaria","genus"),
("Foxtail millet","Setaria","genus"),
("Garlic","Allium","genus"),
("Giant cabuya","Furcraea","genus"),
("Ginger","Zingiber","genus"),
("Gooseberries","Ribes","genus"),
("Grapefruits","Citrus","genus"),
("Grapefruits","Fortunella","genus"),
("Grapefruits","Poncirus","genus"),
("Grapes","Vitis","genus"),
("Grasspea","Lathyrus","genus"),
("Groundnuts","Arachis","genus"),
("Guavas","Psidium","genus"),
("Guayule","Parthenium","genus"),
("Gutta-percha","Palaquium","genus"),
("Hazelnuts","Corylus","genus"),
("Hedysarum","Hedysarum","genus"),
("Hemp","Cannabis","genus"),
("Hops","Humulus","genus"),
("Horseradish","Armoracia","genus"),
("Huckleberry","Gaylussacia","genus"),
("Jack bean","Canavalia","genus"),
("Jackfruit","Artocarpus","genus"),
("Japanese millet","Echinochloa","genus"),
("Jelutong","Dyera","genus"),
("Jerusalem artichoke","Helianthus","genus"),
("Jicama","Pachyrhizus","genus"),
("Jojoba","Simmonsia","genus"),
("Jujube","Zizyphus","genus"),
("Jute","Corchorus","genus"),
("Kaniwa","Chenopodium","genus"),
("Kapok","Ceiba","genus"),
("Karite nuts","Vitellaria","genus"),
("Kenaf","Hibiscus","genus"),
("Kiwi fruit","Actinidia","genus"),
("Kiwicha","Amaranthus","genus"),
("Kodo millet","Paspalum","genus"),
("Kola nuts","Cola","genus"),
("Kumquat","Fortunella","genus"),
("Lablab","Lablab","genus"),
("Lavender","Lavandula","genus"),
("Leeks and other alliaceous vegetables","Allium","genus"),
("Lemons and limes","Citrus","genus"),
("Lentils","Lens","genus"),
("Lespedeza","Lespedeza","genus"),
("Lettuce","Lactuca","genus"),
("Licorice","Glycyrrhiza","genus"),
("Lima bean","Phaseolus","genus"),
("Litchi","Litchi","genus"),
("Lolium","Lolium","genus"),
("Longan","Dimocarpus","genus"),
("Loquat","Eriobotrya","genus"),
("Lotus","Lotus","genus"),
("Lupins","Lupinus","genus"),
("Maca","Lepidium","genus"),
("Macadamia nut","Macadamia","genus"),
("Mahuwa","Madhuca","genus"),
("Maize","Zea","genus"),
("Maize","Tripsacum","genus"),
("Mamey sapote","Pouteria","genus"),
("Mammee","Mammea","genus"),
("Mandarines","Citrus","genus"),
("Mandarines","Fortunella","genus"),
("Mandarines","Poncirus","genus"),
("Mango","Mangifera","genus"),
("Mangosteen","Garcinia","genus"),
("Maple sugar","Acer","genus"),
("Marjoram","Origanum","genus"),
("Mashua","Tropaeolum","genus"),
("Mat bean","Vigna","genus"),
("Mate","Ilex","genus"),
("Mauka","Mirabilis","genus"),
("Medlar","Mespilus","genus"),
("Melilotus","Melilotus","genus"),
("Melons","Cucumis","genus"),
("Mombin","Spondias","genus"),
("Mulberry","Morus","genus"),
("Mung bean","Vigna","genus"),
("Myrtle","Myrtus","genus"),
("Naranjilla","Solanum","genus"),
("New Zealand flax","Phormium","genus"),
("New Zealand spinach","Tetragonia","genus"),
("Noog","Guizotia","genus"),
("Nutmeg","Myristica","genus"),
("Oats","Avena","genus"),
("Oca","Oxalis","genus"),
("Oil palm","Elaeis","genus"),
("Oiticica","Licania","genus"),
("Okra","Abelmoschus","genus"),
("Olives","Olea","genus"),
("Onions","Allium","genus"),
("Onobrychis","Onobrychis","genus"),
("Orache","Atriplex","genus"),
("Orache","Atriplex","genus"),
("Oranges","Citrus","genus"),
("Oranges","Fortunella","genus"),
("Oranges","Poncirus","genus"),
("Oregano","Origanum","genus"),
("Ornithopus","Ornithopus","genus"),
("Papayas","Carica","genus"),
("Parsley","Petroselinum","genus"),
("Parsnip","Pastinaca","genus"),
("Passionfruit","Passiflora","genus"),
("Pawpaw","Asimina","genus"),
("Peaches and nectarines","Prunus","genus"),
("Pearl millet","Cenchrus","genus"),
("Pearl millet","Pennisetum","genus"),
("Pears","Pyrus","genus"),
("Peas","Pisum","genus"),
("Pecan","Carya","genus"),
("Pepper","Piper","genus"),
("Peppermint","Mentha","genus"),
("Perilla","Perilla","genus"),
("Persimmons","Diospyros","genus"),
("Phalaris","Phalaris","genus"),
("Phleum","Phleum","genus"),
("Physic nut","Jatropha","genus"),
("Pigeonpeas","Cajanus","genus"),
("Pili nut","Canarium","genus"),
("Pine nut","Pinus","genus"),
("Pineapples","Ananas","genus"),
("Pistachios","Pistacia","genus"),
("Plantains","Musa","genus"),
("Plums","Prunus","genus"),
("Poa","Poa","genus"),
("Pomegranate","Punica","genus"),
("Pongamia oil","Pongamia","genus"),
("Poppies","Papaver","genus"),
("Potatoes","Solanum","genus"),
("Prickly pear","Opuntia","genus"),
("Proso millet","Panicum","genus"),
("Prosopis","Prosopis","genus"),
("Pueraria","Pueraria","genus"),
("Pumpkin","Cucurbita","genus"),
("Purging croton","Croton","genus"),
("Pyrethrum","Chrysanthemum","genus"),
("Quinces","Cydonia","genus"),
("Quinoa","Chenopodium","genus"),
("Radish","Raphanus","genus"),
("Rambutan","Nephelium","genus"),
("Ramie","Boehmeria","genus"),
("Rapeseed and Mustards","Brassica","genus"),
("Raspberries","Rubus","genus"),
("Rhubarb","Rheum","genus"),
("Rice bean","Vigna","genus"),
("Roselle","Hibiscus","genus"),
("Rosemary","Rosmarinus","genus"),
("Rubber, natural","Hevea","genus"),
("Runner bean","Phaseolus","genus"),
("Rye","Secale","genus"),
("Safflower","Carthamnus","genus"),
("Saffron","Crocus","genus"),
("Sago palm","Metroxylon","genus"),
("Salsify","Tragopogon","genus"),
("Salsola","Salsola","genus"),
("Sapodilla","Manilkara","genus"),
("Savory","Satureja","genus"),
("Service tree","Sorbus","genus"),
("Sesame","Sesamum","genus"),
("Shala tree","Shorea","genus"),
("Sisal","Agave","genus"),
("Snake plant","Sansevieria","genus"),
("Sorghum","Sorghum","genus"),
("Sorrel","Rumex","genus"),
("Soybeans","Glycine","genus"),
("Spinach","Spinacia","genus"),
("Strawberries","Fragaria","genus"),
("Strawberry tree","Arbutus","genus"),
("Sugar beets","Beta","genus"),
("Sugarcane","Saccharum","genus"),
("Sunflowers","Helianthus","genus"),
("Sunn hemp","Crotalaria","genus"),
("Sweetpotatoes","Ipomoea","genus"),
("Sword bean","Canavalia","genus"),
("Tallowtree","Sapium","genus"),
("Tallowtree","Shorea","genus"),
("Tallowtree","Stillingia","genus"),
("Tallowtree","Triadica","genus"),
("Tamarind","Tamarindus","genus"),
("Taro","Colocasia","genus"),
("Tarragon","Artemisia","genus"),
("Tea","Camellia","genus"),
("Teff","Eragrostis","genus"),
("Tepary bean","Phaseolus","genus"),
("Thyme","Thymus","genus"),
("Tobacco","Nicotiana","genus"),
("Tomatillo","Physalis","genus"),
("Tomatoes","Solanum","genus"),
("Tripsacum","Tripsacum","genus"),
("Triticale","Triticosecale","genus"),
("Triticale","xTriticosecale","genus"),
("Tung nuts","Aleurites","genus"),
("Tung nuts","Vernicia","genus"),
("Turmeric","Curcuma","genus"),
("Turnips","Brassica","genus"),
("Ulluco","Ullucus","genus"),
("Vanilla","Vanilla","genus"),
("Velvet bean","Mucuna","genus"),
("Velvet leaf","Abutilon","genus"),
("Vetch","Vicia","genus"),
("Walnuts","Juglans","genus"),
("Watercress","Nasturtium","genus"),
("Watermelons","Citrullus","genus"),
("Wheat","Triticum","genus"),
("Wheat","Aegilops","genus"),
("Wheat","Amblyopyrum","genus"),
("Wheat","Agropyron","genus"),
("Wheat","Elymus","genus"),
("Wheat","Leymus","genus"),
("Wheat","Secale","genus"),
("Wheat","Thinopyrum","genus"),
("Wildrice","Zizania","genus"),
("Winged bean","Psophocarpus","genus"),
("Yacon","Smallanthus","genus"),
("Yams","Dioscorea","genus"),
("Yautia, cocoyam","Xanthosoma","genus"),
("Year bean","Phaseolus","genus"),
("Zucchini","Cucurbita","genus"),
("Abaca","Musa textilis","taxonName"),
("Achira","Canna edulis","taxonName"),
("Ackee","Blighia sapida","taxonName"),
("Adlay","Coix lacryma-jobi","taxonName"),
("Adzuki bean","Vigna angularis","taxonName"),
("African rice","Oryza glaberimma","taxonName"),
("Agave","Agave foetida","taxonName"),
("Agave","Agave letonae","taxonName"),
("Agave","Agave americana","taxonName"),
("Agave","Agave cantala","taxonName"),
("Agave","Agave fourcroydes","taxonName"),
("Agave","Agave lecheguilla","taxonName"),
("Agropyron","Agropyron cristatum","taxonName"),
("Agropyron","Agropyron desertorum","taxonName"),
("Agrostis","Agrostis stolonifera","taxonName"),
("Agrostis","Agrostis tenuis","taxonName"),
("Albardine","Lygeum spartum","taxonName"),
("Alfalfa","Medicago sativa","taxonName"),
("Alfalfa","Medicago truncatula","taxonName"),
("Alfalfa","Medicago rigidula","taxonName"),
("Alfalfa","Medicago scutellata","taxonName"),
("Alfalfa","Medicago falcata","taxonName"),
("Alfalfa","Medicago arborea","taxonName"),
("Allspice","Pimenta dioica","taxonName"),
("Almonds","Prunus dulcis","taxonName"),
("Alopecurus","Alopecurus pratensis","taxonName"),
("Amaranth","Amaranthus cruentus","taxonName"),
("Amaranth","Amaranthus tricolor","taxonName"),
("Amaranth","Amaranthus dubius","taxonName"),
("Amaranth","Amaranthus blitum","taxonName"),
("Amaranth","Amaranthus cruentus","taxonName"),
("Amaranth","Amaranthus hypochondriacus","taxonName"),
("Andropogon","Andropogon gayanus","taxonName"),
("Anise","Pimpinella anisum","taxonName"),
("Apple","Malus domestica","taxonName"),
("Apricot","Prunus armeniaca","taxonName"),
("Areca nuts","Areca catechu","taxonName"),
("Arracacha","Arracacoa xanthorrhiza","taxonName"),
("Arrhenatherum","Arrhenatherum elatius","taxonName"),
("Arrowroot","Maranta arundinacea","taxonName"),
("Artichokes","Cynara cardunculus","taxonName"),
("Asian rice","Oryza sativa","taxonName"),
("Asparagus","Asparagus officinalis","taxonName"),
("Astragalus","Astragalus chinensis","taxonName"),
("Astragalus","Astragalus arenarius","taxonName"),
("Astragalus","Astragalus cicer","taxonName"),
("Atriplex","Atriplex halimus","taxonName"),
("Atriplex","Atriplex nummularia","taxonName"),
("Avocado","Persea americana","taxonName"),
("Azarole","Crataegus azarolus","taxonName"),
("Babaco","Vasconcellea xheilbornii","taxonName"),
("Babaco","Carica pentagona","taxonName"),
("Badian","Illicium verum","taxonName"),
("Bambara bean","Vigna subterranea","taxonName"),
("Bamboo shoot","Bambusa vulgaris","taxonName"),
("Bamboo shoot","Phyllostachys edulis","taxonName"),
("Bananas","Musa acuminata","taxonName"),
("Barley","Hordeum vulgare","taxonName"),
("Basil","Ocimum basilicum","taxonName"),
("Bay leaf","Laurus nobilis","taxonName"),
("Beech nut","Fagus sylvatica","taxonName"),
("Beets","Beta vulgaris","taxonName"),
("Black gram","Vigna mungo","taxonName"),
("Black salsify","Scorzonera hispanica","taxonName"),
("Blueberry","Vaccinium corymbosum","taxonName"),
("Brazil nut","Bertholletia excelsa","taxonName"),
("Breadfruit","Artocarpus altilis","taxonName"),
("Buckwheat","Fagopyrum esculentum","taxonName"),
("Butter-nut","Caryocar nuciferum","taxonName"),
("Butternut squash","Cucurbita moschata","taxonName"),
("Cabbages","Brassica oleracea","taxonName"),
("Cabbages and other brassicas","Brassica oleracea","taxonName"),
("Cabbages and other brassicas","Brassica napus","taxonName"),
("Cabbages and other brassicas","Brassica carinata","taxonName"),
("Cabbages and other brassicas","Brassica juncea","taxonName"),
("Cabbages and other brassicas","Brassica rapa","taxonName"),
("Caesarweed","Urena lobata","taxonName"),
("Caesarweed","Urena sinuata","taxonName"),
("Cainito","Chrysophyllum cainito","taxonName"),
("Calabash","Lagenaria siceraria","taxonName"),
("Canary seed","Phalaris canariensis","taxonName"),
("Candlenut","Aleurites moluccanus","taxonName"),
("Canola","Brassica juncea","taxonName"),
("Capers","Capparis spinosa","taxonName"),
("Carambola","Averrhoa carambola","taxonName"),
("Carapa","Carapa guianensis","taxonName"),
("Cardamoms","Amomum subulatum","taxonName"),
("Cardamoms","Elettaria cardamomum","taxonName"),
("Carneros Yucca","Samuela carnerosana","taxonName"),
("Carneros Yucca","Yucca carnerosana","taxonName"),
("Caroa","Neoglaziovia variegata","taxonName"),
("Carobs","Ceratonia siliqua","taxonName"),
("Carrots","Daucus carota","taxonName"),
("Cashews","Anacardium occidentale","taxonName"),
("Cassava","Manihot esculenta","taxonName"),
("Castor bean","Ricinus communis","taxonName"),
("Ceara","Manihot glaziovii","taxonName"),
("Ceara","Manihot carthagenensis","taxonName"),
("Celery","Apium graveolens","taxonName"),
("Chayote","Sechium edule","taxonName"),
("Cherimoya","Annona cherimola","taxonName"),
("Cherries","Prunus avium","taxonName"),
("Cherries","Prunus cerasus","taxonName"),
("Chervil","Anthriscus cerefolium","taxonName"),
("Chestnuts","Castanea sativa","taxonName"),
("Chickpeas","Cicer arietinum","taxonName"),
("Chicle","Achras zapota","taxonName"),
("Chicory","Cichorium intybus","taxonName"),
("Chicory","Cichorium endivia","taxonName"),
("Chillies and peppers","Capsicum annuum","taxonName"),
("Chillies and peppers","Capsicum pubescens","taxonName"),
("Chillies and peppers","Capsicum baccatum","taxonName"),
("Chillies and peppers","Capsicum frutescens","taxonName"),
("Chillies and peppers","Capsicum chinense","taxonName"),
("Chinotto","Citrus myrtifolia","taxonName"),
("Chontadura","Astrocaryum standleyanum","taxonName"),
("Chufa","Cyperus esculentus","taxonName"),
("Cinnamon","Cinnamomum cassia","taxonName"),
("Cinnamon","Cinnamomum verum","taxonName"),
("Citron","Citrus medica","taxonName"),
("Citronella","Cymbopogon nardus","taxonName"),
("Citronella","Cymbopogon citratus","taxonName"),
("Citronella","Cymbopogon winterianus","taxonName"),
("Clovers","Trifolium repens","taxonName"),
("Clovers","Trifolium pratense","taxonName"),
("Clovers","Trifolium alexandrinum","taxonName"),
("Clovers","Trifolium alpestre","taxonName"),
("Clovers","Trifolium ambiguum","taxonName"),
("Clovers","Trifolium angustifolium","taxonName"),
("Clovers","Trifolium arvense","taxonName"),
("Clovers","Trifolium agrocicerum","taxonName"),
("Clovers","Trifolium hybridum","taxonName"),
("Clovers","Trifolium vesiculosum","taxonName"),
("Clovers","Trifolium subterraneum","taxonName"),
("Clovers","Trifolium semipilosum","taxonName"),
("Clovers","Trifolium rueppellianum","taxonName"),
("Clovers","Trifolium incarnatum","taxonName"),
("Clovers","Trifolium resupinatum","taxonName"),
("Clovers","Trifolium pratense","taxonName"),
("Clovers","Trifolium repens","taxonName"),
("Cloves","Syzygium aromaticum","taxonName"),
("Cocoa","Theobroma cacao","taxonName"),
("Coconuts","Cocos nucifera","taxonName"),
("Coffee","Coffea arabica","taxonName"),
("Coffee","Coffea canephora","taxonName"),
("Common bean","Phaseolus vulgaris","taxonName"),
("Coriander","Coriandrum sativum","taxonName"),
("Coronilla","Coronilla varia","taxonName"),
("Cotton","Gossypium hirsutum","taxonName"),
("Cotton","Gossypium herbaceum","taxonName"),
("Cowpeas","Vigna unguiculata","taxonName"),
("Cranberries","Vaccinium macrocarpon","taxonName"),
("Cress","Lepidium sativum","taxonName"),
("Cucumbers and gherkins","Cucumis sativus","taxonName"),
("Cumin","Cuminum cyminum","taxonName"),
("Currants","Ribes nigrum","taxonName"),
("Currants","Ribes rubrum","taxonName"),
("Dactylis","Dactylis glomerata","taxonName"),
("Dates","Phoenix dactylifera","taxonName"),
("Devil's cotton","Abroma augustum","taxonName"),
("Dill","Anethum graveolens","taxonName"),
("Durian","Durio zibethinus","taxonName"),
("Eggplant","Solanum melongena","taxonName"),
("Elderberry","Sambucus nigra","taxonName"),
("Esparto","Stipa tenacissima","taxonName"),
("Ethiopian rape","Brassica carinata","taxonName"),
("Faba beans","Vicia faba","taxonName"),
("Feijoa","Acca sellowiana","taxonName"),
("Fennel","Foeniculum vulgare","taxonName"),
("Fenugreek","Trigonella foenum-graecum","taxonName"),
("Festuca","Festuca arundinacea","taxonName"),
("Festuca","Festuca rubra","taxonName"),
("Festuca","Festuca pratensis","taxonName"),
("Festuca","Festuca ovina","taxonName"),
("Festuca","Festuca heterophylla","taxonName"),
("Festuca","Festuca gigantea","taxonName"),
("Figs","Ficus carica","taxonName"),
("Finger millet","Eleusine coracana","taxonName"),
("Fique","Furcraea macrophylla","taxonName"),
("Flax","Linum usitatissimum","taxonName"),
("Fonio","Digitaria exilis","taxonName"),
("Fonio","Digitaria iburua","taxonName"),
("Foxtail millet","Setaria italica","taxonName"),
("Garlic","Allium sativum","taxonName"),
("Giant cabuya","Furcraea foetida","taxonName"),
("Ginger","Zingiber officinale","taxonName"),
("Gooseberries","Ribes uva-crispa","taxonName"),
("Grapefruits","Citrus paradisi","taxonName"),
("Grapefruits","Citrus xparadisi","taxonName"),
("Grapes","Vitis vinifera","taxonName"),
("Grasspea","Lathyrus sativus","taxonName"),
("Groundnuts","Arachis hypogaea","taxonName"),
("Guavas","Psidium guajava","taxonName"),
("Guayule","Parthenium argentatum","taxonName"),
("Gutta-percha","Palaquium gutta","taxonName"),
("Hazelnuts","Corylus avellana","taxonName"),
("Hedysarum","Hedysarum coronarium","taxonName"),
("Hemp","Cannabis sativa","taxonName"),
("Hops","Humulus lupulus","taxonName"),
("Horseradish","Armoracia rusticana","taxonName"),
("Huckleberry","Gaylussacia baccata","taxonName"),
("Jack bean","Canavalia ensiformis","taxonName"),
("Jackfruit","Artocarpus heterophyllus","taxonName"),
("Japanese millet","Echinochloa frumentacea","taxonName"),
("Japanese millet","Echinochloa esculenta","taxonName"),
("Jelutong","Dyera costulata","taxonName"),
("Jerusalem artichoke","Helianthus tuberosus","taxonName"),
("Jicama","Pachyrhizus erosus","taxonName"),
("Jojoba","Simmondsia chinensis","taxonName"),
("Jujube","Zizyphus jujuba","taxonName"),
("Jute","Corchorus olitorius","taxonName"),
("Jute","Corchorus capsularis","taxonName"),
("Kaniwa","Chenopodium pallidicaule","taxonName"),
("Kapok","Ceiba pentandra","taxonName"),
("Karite nuts","Vitellaria paradoxa","taxonName"),
("Kenaf","Hibiscus cannabinus","taxonName"),
("Kiwi fruit","Actinidea deliciosa","taxonName"),
("Kiwi fruit","Actinidia chinensis","taxonName"),
("Kiwicha","Amaranthus caudatus","taxonName"),
("Kodo millet","Paspalum scrobiculatum","taxonName"),
("Kola nuts","Cola acuminata","taxonName"),
("Kola nuts","Cola verticillata","taxonName"),
("Kola nuts","Cola nitida","taxonName"),
("Kola nuts","Cola anomala","taxonName"),
("Kumquat","Fortunella japonica","taxonName"),
("Lablab","Lablab purpureus","taxonName"),
("Lavender","Lavandula spica","taxonName"),
("Leeks and other alliaceous vegetables","Allium porrum","taxonName"),
("Leeks and other alliaceous vegetables","Allium schoenoprasum","taxonName"),
("Lemons and limes","Citrus limon","taxonName"),
("Lemons and limes","Citrus xlimon","taxonName"),
("Lemons and limes","Citrus aurantiifolia","taxonName"),
("Lentils","Lens culinaris","taxonName"),
("Lespedeza","Lespedeza cuneata","taxonName"),
("Lespedeza","Lespedeza stipulacea","taxonName"),
("Lespedeza","Lespedeza striata","taxonName"),
("Lettuce","Lactuca sativa","taxonName"),
("Licorice","Glycyrrhiza glabra","taxonName"),
("Lima bean","Phaseolus lunatus","taxonName"),
("Litchi","Litchi chinensis","taxonName"),
("Lolium","Lolium hybridum","taxonName"),
("Lolium","Lolium temulentum","taxonName"),
("Lolium","Lolium rigidum","taxonName"),
("Lolium","Lolium perenne","taxonName"),
("Lolium","Lolium multiflorum","taxonName"),
("Longan","Dimocarpus longan","taxonName"),
("Loquat","Eriobotrya japonica","taxonName"),
("Lotus","Lotus corniculatus","taxonName"),
("Lotus","Lotus uliginosus","taxonName"),
("Lotus","Lotus subbiflorus","taxonName"),
("Lupins","Lupinus mutabilis","taxonName"),
("Lupins","Lupinus luteus","taxonName"),
("Lupins","Lupinus angustifolius","taxonName"),
("Lupins","Lupinus albus","taxonName"),
("Maca","Lepidium meyenii","taxonName"),
("Macadamia nut","Macadamia integrifolia","taxonName"),
("Macadamia nut","Macadamia tetraphylla","taxonName"),
("Mahuwa","Madhuca longifolia","taxonName"),
("Maize","Zea mays","taxonName"),
("Mamey sapote","Pouteria sapota","taxonName"),
("Mammee","Mammea americana","taxonName"),
("Mandarines","Citrus reticulata","taxonName"),
("Mango","Mangifera indica","taxonName"),
("Mangosteen","Garcinia mangostana","taxonName"),
("Maple sugar","Acer saccharum","taxonName"),
("Marjoram","Origanum majorana","taxonName"),
("Mashua","Tropaeolum tuberosum","taxonName"),
("Mat bean","Vigna aconitifolia","taxonName"),
("Mate","Ilex paraguariensis","taxonName"),
("Mauka","Mirabilis expansa","taxonName"),
("Medlar","Mespilus germanica","taxonName"),
("Melilotus","Melilotus albus","taxonName"),
("Melilotus","Melilotus officinalis","taxonName"),
("Melons","Cucumis melo","taxonName"),
("Mombin","Spondias mombin","taxonName"),
("Mombin","Spondias purpurea","taxonName"),
("Mulberry","Morus nigra","taxonName"),
("Mulberry","Morus rubra","taxonName"),
("Mulberry","Morus alba","taxonName"),
("Mung bean","Vigna radiata","taxonName"),
("Myrtle","Myrtus communis","taxonName"),
("Naranjilla","Solanum quitoense","taxonName"),
("New Zealand flax","Phormium tenax","taxonName"),
("New Zealand spinach","Tetragonia tetragonoides","taxonName"),
("Noog","Guizotia abyssinica","taxonName"),
("Nutmeg","Myristica fragrans","taxonName"),
("Oats","Avena sativa","taxonName"),
("Oca","Oxalis tuberosa","taxonName"),
("Oil palm","Elaeis guineensis","taxonName"),
("Oil palm","Elaeis oleifera","taxonName"),
("Oiticica","Licania rigida","taxonName"),
("Okra","Abelmoschus esculentus","taxonName"),
("Olives","Olea europaea","taxonName"),
("Onions","Allium cepa","taxonName"),
("Onobrychis","Onobrychis viciifolia","taxonName"),
("Orache","Atriplex patula","taxonName"),
("Orache","Atriplex hortensis","taxonName"),
("Oranges","Citrus sinensis","taxonName"),
("Oranges","Citrus xsinensis","taxonName"),
("Oregano","Origanum vulgare","taxonName"),
("Ornithopus","Ornithopus sativus","taxonName"),
("Papayas","Carica papaya","taxonName"),
("Parsley","Petroselinum crispum","taxonName"),
("Parsnip","Pastinaca sativa","taxonName"),
("Passionfruit","Passiflora edulis","taxonName"),
("Pawpaw","Asimina triloba","taxonName"),
("Peaches and nectarines","Prunus persica","taxonName"),
("Pearl millet","Cenchrus americanus","taxonName"),
("Pearl millet","Pennisetum glaucum","taxonName"),
("Pearl millet","Pennisetum glaucum","taxonName"),
("Pears","Pyrus communis","taxonName"),
("Peas","Pisum sativum","taxonName"),
("Pecan","Carya illinoinensis","taxonName"),
("Pepper","Piper nigrum","taxonName"),
("Peppermint","Mentha xpiperita","taxonName"),
("Peppermint","Mentha piperita","taxonName"),
("Perilla","Perilla frutescens","taxonName"),
("Persimmons","Diospyros kaki","taxonName"),
("Phalaris","Phalaris aquatica","taxonName"),
("Phalaris","Phalaris arundinacea","taxonName"),
("Phleum","Phleum pratense","taxonName"),
("Physic nut","Jatropha curcas","taxonName"),
("Pigeonpeas","Cajanus cajan","taxonName"),
("Pili nut","Canarium indicum","taxonName"),
("Pili nut","Canarium harveyi","taxonName"),
("Pili nut","Canarium ovatum","taxonName"),
("Pine nut","Pinus pinea","taxonName"),
("Pineapples","Ananas comosus","taxonName"),
("Pistachios","Pistacia vera","taxonName"),
("Plantains","Musa balbisiana","taxonName"),
("Plums","Prunus domestica","taxonName"),
("Poa","Poa alpina","taxonName"),
("Poa","Poa pratensis","taxonName"),
("Poa","Poa annua","taxonName"),
("Pomegranate","Punica granatum","taxonName"),
("Pongamia oil","Pongamia glabra","taxonName"),
("Poppies","Papaver somniferum","taxonName"),
("Potatoes","Solanum tuberosum","taxonName"),
("Potatoes","Solanum curtilobum","taxonName"),
("Potatoes","Solanum juzepczukii","taxonName"),
("Potatoes","Solanum ajanhuiri","taxonName"),
("Prickly pear","Opuntia ficus-indica","taxonName"),
("Proso millet","Panicum miliaceum","taxonName"),
("Prosopis","Prosopis affinis","taxonName"),
("Prosopis","Prosopis pallida","taxonName"),
("Prosopis","Prosopis nigra","taxonName"),
("Prosopis","Prosopis chilensis","taxonName"),
("Prosopis","Prosopis alba","taxonName"),
("Pueraria","Pueraria phaseoloides","taxonName"),
("Pumpkin","Cucurbita maxima","taxonName"),
("Purging croton","Croton tiglium","taxonName"),
("Pyrethrum","Chrysanthemum cinerariifolium","taxonName"),
("Quinces","Cydonia oblonga","taxonName"),
("Quinoa","Chenopodium quinoa","taxonName"),
("Radish","Raphanus sativus","taxonName"),
("Rambutan","Nephelium lappaceum","taxonName"),
("Ramie","Boehmeria nivea","taxonName"),
("Rapeseed and Mustards","Brassica napus","taxonName"),
("Rapeseed and Mustards","Brassica rapa","taxonName"),
("Raspberries","Rubus idaeus","taxonName"),
("Raspberries","Rubus plicatus","taxonName"),
("Rhubarb","Rheum rhabarbarum","taxonName"),
("Rice bean","Vigna umbellata","taxonName"),
("Roselle","Hibiscus sabdariffa","taxonName"),
("Rosemary","Rosmarinus officinalis","taxonName"),
("Rubber, natural","Hevea brasiliensis","taxonName"),
("Runner bean","Phaseolus coccineus","taxonName"),
("Rye","Secale cereale","taxonName"),
("Safflower","Carthamus tinctorius","taxonName"),
("Saffron","Crocus sativus","taxonName"),
("Sago palm","Metroxylon sagu","taxonName"),
("Salsify","Tragopogon porrifolius","taxonName"),
("Salsola","Salsola vermiculata","taxonName"),
("Sapodilla","Manilkara zapota","taxonName"),
("Savory","Satureja hortensis","taxonName"),
("Savory","Satureja montana","taxonName"),
("Service tree","Sorbus domestica","taxonName"),
("Sesame","Sesamum indicum","taxonName"),
("Shala tree","Shorea robusta","taxonName"),
("Sisal","Agave sisalana","taxonName"),
("Snake plant","Sansevieria trifasciata","taxonName"),
("Sorghum","Sorghum bicolor","taxonName"),
("Sorrel","Rumex acetosa","taxonName"),
("Soybeans","Glycine max","taxonName"),
("Spinach","Spinacia oleracea","taxonName"),
("Strawberries","Fragaria xananassa","taxonName"),
("Strawberries","Fragaria ananassa","taxonName"),
("Strawberry tree","Arbutus unedo","taxonName"),
("Sugar beets","Beta vulgaris","taxonName"),
("Sugarcane","Saccharum officinarum","taxonName"),
("Sunflowers","Helianthus annuus","taxonName"),
("Sunn hemp","Crotalaria juncea","taxonName"),
("Sweetpotatoes","Ipomoea batatas","taxonName"),
("Sword bean","Canavalia gladiata","taxonName"),
("Tallowtree","Triadica sebifera","taxonName"),
("Tallowtree","Stillingia sebifera","taxonName"),
("Tallowtree","Sapium sebiferum","taxonName"),
("Tallowtree","Shorea stenocarpa","taxonName"),
("Tallowtree","Shorea aptera","taxonName"),
("Tallowtree","Sapium sebiferum","taxonName"),
("Tallowtree","Shorea aptera","taxonName"),
("Tallowtree","Shorea stenocarpa","taxonName"),
("Tallowtree","Stillingia sebifera","taxonName"),
("Tamarind","Tamarindus indica","taxonName"),
("Taro","Colocasia esculenta","taxonName"),
("Tarragon","Artemisia dracunculus","taxonName"),
("Tea","Camellia sinensis","taxonName"),
("Teff","Eragrostis tef","taxonName"),
("Tepary bean","Phaseolus acutifolius","taxonName"),
("Thyme","Thymus vulgaris","taxonName"),
("Tobacco","Nicotiana tabacum","taxonName"),
("Tomatillo","Physalis philadelphica","taxonName"),
("Tomatillo","Physalis ixocarpa","taxonName"),
("Tomatoes","Solanum lycopersicum","taxonName"),
("Tripsacum","Tripsacum laxum","taxonName"),
("Triticale","×Triticosecale blaringhemii","taxonName"),
("Triticale","Triticosecale schlanstedtense","taxonName"),
("Triticale","×Triticosecale neoblaringhemii","taxonName"),
("Triticale","×Triticosecale semisecale","taxonName"),
("Triticale","×Triticosecale schlanstedtense","taxonName"),
("Triticale","Triticosecale blaringhemii","taxonName"),
("Triticale","Triticosecale neoblaringhemii","taxonName"),
("Triticale","Triticosecale semisecale","taxonName"),
("Tung nuts","Vernicia fordii","taxonName"),
("Tung nuts","Aleurites fordii","taxonName"),
("Tung nuts","Aleurites fordii","taxonName"),
("Turmeric","Curcuma longa","taxonName"),
("Turnips","Brassica rapa","taxonName"),
("Ulluco","Ullucus tuberosus","taxonName"),
("Vanilla","Vanilla planifolia","taxonName"),
("Vanilla","Vanilla tahitensis","taxonName"),
("Vanilla","Vanilla xtahitensis","taxonName"),
("Vanilla","Vanilla pompona","taxonName"),
("Velvet bean","Mucuna pruriens","taxonName"),
("Velvet leaf","Abutilon theophrasti","taxonName"),
("Vetch","Vicia sativa","taxonName"),
("Walnuts","Juglans regia","taxonName"),
("Watercress","Nasturtium officinale","taxonName"),
("Watermelons","Citrullus lanatus","taxonName"),
("Watermelons","Citrullus vulgaris","taxonName"),
("Wheat","Triticum ×petropavlovskyi","taxonName"),
("Wheat","Triticum zhukovsky","taxonName"),
("Wheat","Triticum vavilovii","taxonName"),
("Wheat","Triticum timopheevii","taxonName"),
("Wheat","Triticum aestivum","taxonName"),
("Wheat","Triticum turgidum","taxonName"),
("Wheat","Triticum durum","taxonName"),
("Wheat","Triticum flaksbergeri","taxonName"),
("Wheat","Triticum ispahanicum","taxonName"),
("Wheat","Triticum kiharae","taxonName"),
("Wheat","Triticum monococcum","taxonName"),
("Wildrice","Zizania palustris","taxonName"),
("Winged bean","Psophocarpus tetragonolobus","taxonName"),
("Yacon","Smallanthus sonchifolius","taxonName"),
("Yams","Dioscorea rotundata","taxonName"),
("Yams","Dioscorea alata","taxonName"),
("Yams","Dioscorea cayennensis","taxonName"),
("Yautia, cocoyam","Xanthosoma sagittifolium","taxonName"),
("Year bean","Phaseolus dumosus","taxonName"),
("Zucchini","Cucurbita pepo","taxonName");




