INSERT INTO genesys_2018.CIAT_crop_taxa(name, taxa, level)
values ("Agave","Agave","genus"),
("Alfalfa","Medicago","genus"),
("Anise, badian, fennel, coriander","Pimpinella","genus"),
("Anise, badian, fennel, coriander","Illicium","genus"),
("Anise, badian, fennel, coriander","Foeniculum","genus"),
("Anise, badian, fennel, coriander","Coriandrum","genus"),
("Apple","Malus","genus"),
("Areca nuts","Areca","genus"),
("Artichokes","Cynara","genus"),
("Asparagus","Asparagus","genus"),
("Avocado","Persea","genus"),
("Barley","Hordeum","genus"),
("Beans","Phaseolus","genus"),
("Beets","Beta","genus"),
("Brazil nut","Bertholletia","genus"),
("Buckwheat","Fagopyrum","genus"),
("Cabbages and other brassicas","Brassica","genus"),
("Canary seed","Phalaris","genus"),
("Carobs","Ceratonia","genus"),
("Cassava","Manihot","genus"),
("Castor bean","Ricinus","genus"),
("Chestnut","Castanea","genus"),
("Chickpea","Cicer","genus"),
("Chillies and peppers","Capsicum","genus"),
("Cinnamon","Cinnamomum","genus"),
("Citronella","Cymbopogon","genus"),
("Clove","Syzygium","genus"),
("Clover","Trifolium","genus"),
("Cocoa","Theobroma","genus"),
("Coconut","Cocos","genus"),
("Coffee","Coffea","genus"),
("Cotton","Gossypium","genus"),
("Currant","Ribes","genus"),
("Dates","Phoenix","genus"),
("Fig","Ficus","genus"),
("Flax","Linum","genus"),
("Fonio","Digitaria","genus"),
("Ginger","Zingiber","genus"),
("Gooseberry","Ribes","genus"),
("Grape","Vitis","genus"),
("Groundnut","Arachis","genus"),
("Hazelnuts","Corylus","genus"),
("Hemp","Cannabis","genus"),
("Hops","Humulus","genus"),
("Jojoba","Simmonsia","genus"),
("Jute","Corchorus","genus"),
("Kapok","Ceiba","genus"),
("Karite nut","Vitellaria","genus"),
("Kiwi fruit","Actinidia","genus"),
("Kola nuts","Cola","genus"),
("Lentil","Lens","genus"),
("Lettuce and chicory","Lactuca","genus"),
("Lettuce and chicory","Chicorium","genus"),
("Lupin","Lupinus","genus"),
("Maize","Zea","genus"),
("Maize","Tripsacum","genus"),
("Mangoes, mangosteens, guavas","Mangifera","genus"),
("Mangoes, mangosteens, guavas","Garcinia","genus"),
("Mangoes, mangosteens, guavas","Psidium","genus"),
("Mate","Ilex","genus"),
("Millet","Pennisetum","genus"),
("Millet","Eleusine","genus"),
("Millet","Cenchrus","genus"),
("Millet","Digitaria","genus"),
("Millet","Panicum","genus"),
("Millet","Setaria","genus"),
("Millet","Echinochloa","genus"),
("Millet","Paspalum","genus"),
("Nutmeg, mace, cardamoms","Myristica","genus"),
("Nutmeg, mace, cardamoms","Cardamom","genus"),
("Oats","Avena","genus"),
("Oil palm","Elaeis","genus"),
("Okra","Abelmoschus","genus"),
("Olive","Olea","genus"),
("Papaya","Carica","genus"),
("Pea","Pisum","genus"),
("Pear","Pyrus","genus"),
("Pearl millet","Pennisetum","genus"),
("Pepper","Piper","genus"),
("Peppermint","Mentha","genus"),
("Persimmons","Diospyrus","genus"),
("Pigeonpeas","Cajanus","genus"),
("Pineapple","Ananas","genus"),
("Pistachio","Pistacia","genus"),
("Poppy","Papaver","genus"),
("Pumpkins, squash, gourds","Cucurbita","genus"),
("Pumpkins, squash, gourds","Lagenaria","genus"),
("Pyrethrum","Chrysanthemum","genus"),
("Quinces","Cydonia","genus"),
("Quinoa","Chenopodium","genus"),
("Ramie","Boehmeria","genus"),
("Raspberry","Rubus","genus"),
("Rice","Oryza","genus"),
("Roots, Other","Xanthosoma","genus"),
("Roots, Other","Colocasia","genus"),
("Rubber, natural","Hevea","genus"),
("Rye","Secale","genus"),
("Safflower","Carthamnus","genus"),
("Sesame","Sesamum","genus"),
("Sisal","Agave","genus"),
("Sorghum","Sorghum","genus"),
("Soybean","Glycine","genus"),
("Spinach","Spinacia","genus"),
("Strawberry","Fragaria","genus"),
("Sugar beet","Beta","genus"),
("Sugar maple","Acer","genus"),
("Sugarcane","Saccharum","genus"),
("Sunflower","Helianthus","genus"),
("Sweetpotato","Ipomoea","genus"),
("Tallow","Triadica","genus"),
("Taro","Colocasia","genus"),
("Tea","Camellia","genus"),
("Tea and mate","Camellia","genus"),
("Tea and mate","Ilex","genus"),
("Tobacco","Nicotiana","genus"),
("Treenuts","Carya","genus"),
("Treenuts","Juglans","genus"),
("Treenuts","Bertholletia","genus"),
("Treenuts","Anacardium","genus"),
("Treenuts","Pistacia","genus"),
("Treenuts","Corylus","genus"),
("Treenuts","Castanea","genus"),
("Triticale","Triticosecale","genus"),
("Triticale","xTriticosecale","genus"),
("Tung","Vernicia","genus"),
("Vanilla","Vanilla","genus"),
("Walnut","Juglans","genus"),
("Watermelon","Citrullus","genus"),
("Wheat","Triticum","genus"),
("Wheat","Aegilops","genus"),
("Wheat","Thinopyrum","genus"),
("Yams","Dioscorea","genus"),
("Yautia, cocoyam","Xanthosoma","genus"),
("Carrots and turnips","Daucus","genus"),
("Carrots and turnips","Brassica rapa","taxonName"),
("Abaca","Musa textilis","taxonName"),
("Almond","Prunus dulcis","taxonName"),
("Apricot","Prunus armeniaca","taxonName"),
("Bambara bean","Vigna subterranea","taxonName"),
("Bananas","Musa acuminata","taxonName"),
("Blueberry","Vaccinium corymbosum","taxonName"),
("Cashew","Anacardium occidentale","taxonName"),
("Cherry","Prunus avium","taxonName"),
("Cowpea","Vigna unguiculata","taxonName"),
("Cranberry","Vaccinium macrocarpon","taxonName"),
("Cucumbers and gherkins","Cucumis sativus","taxonName"),
("Eggplant","Solanum melongena","taxonName"),
("Faba bean","Vicia faba","taxonName"),
("Garlic","Allium sativum","taxonName"),
("Grapefruit","Citrus paradisi","taxonName"),
("Leeks and other alliaceous vegetables","Allium porrum","taxonName"),
("Lemons and limes","Citrus limon","taxonName"),
("Lemons and limes","Citrus aurantiifolia","taxonName"),
("Melons","Cucumis melo","taxonName"),
("Onions","Allium cepa","taxonName"),
("Oranges and mandarines","Citrus sinensis","taxonName"),
("Oranges and mandarines","Citrus reticulata","taxonName"),
("Peaches and nectarines","Prunus persica","taxonName"),
("Plantains","Musa balbisiana","taxonName"),
("Plums","Prunus domestica","taxonName"),
("Potato","Solanum tuberosum","taxonName"),
("Pulses, Other","Vigna unguiculata","taxonName"),
("Pulses, Other","Cicer arietinum","taxonName"),
("Pulses, Other","Lens culinaris","taxonName"),
("Pulses, Other","Vicia faba","taxonName"),
("Pulses, Other","Cajanus cajan","taxonName"),
("Pulses, Other","Vigna angularis","taxonName"),
("Pulses, Other","Vigna radiata","taxonName"),
("Pulses, Other","Vigna subterranea","taxonName"),
("Rapeseed and Mustard","Brassica napus","taxonName"),
("Rapeseed and Mustard","Brassica rapa","taxonName"),
("Tomato","Solanum lycopersicum","taxonName"),
("Turnip","Brassica rapa","taxonName"),
("Vetch","Vicia sativa","taxonName");